services:
    sonata.admin.series:
        class: AppBundle\Admin\SeriesAdmin
        arguments: [~, AppBundle\Entity\Series, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Series", label: "Series" }
